_integrations/appdynamics.md

@noamshemesh correct me if I'm wrong, but this is a relic from the past, right?

Done and install button is not longer there

---

_integrations/agent-common/configure-agent/generic.md

*/objects plugin must be enabled

---

_integrations/agent-common/install/agent-install-centos.md
_integrations/agent-common/start-and-summary/agent-start-centos.md
_integrations/nagios-centos.md

@shaharke Please test in frontier, 10x

Documentation fixes for centos5

---

_integrations/agent-common/configure-agent/common.md
_integrations/agent-common/configure-agent/icinga2.md
_integrations/icinga-centos.md
_integrations/icinga-debian.md
_integrations/icinga-ubuntu.md
_integrations/icinga.md
_integrations/icinga/common.md
_integrations/icinga2-centos.md
_integrations/icinga2-debian.md
_integrations/icinga2-ubuntu.md
_integrations/icinga2.md
_integrations/icinga2/beta.md
_integrations/icinga2/common.md

@dshush @dturchin please review. You can also find the documentation here: http://bp-docs-staging.s3-website-us-west-1.amazonaws.com/feature/icinga2_fix/integrations/index.html#icinga---centos-

Icinga2 documentation

---

_integrations/newrelic.md

Disabled auto expiration, so we need to change the tutorial

---

_integrations/librato.md

@dshush @dturchin Librato tutorial. Please review.

Added tutorial for Librato

---

_integrations/solarwinds.md

@dshush Please review. Adding comment about Orion server version support.

Adding comment about minimum supported Orion server version.

---

_integrations/splunk-6-3-and-up.md

Please review & merge @erikzaadi @shaharke

Minor formatting and edits

---

_integrations/splunk.md

@erikzaadi @shaharke : some changes to try to address the formatting issues with the old tutorial. Please review and merge if appropriate or let me know if additional changes are required. I also sent an email to Benga.
FYI, I'll be in surgery tomorrow and I'm not sure how I'll feel the rest of the week, so there may be some delay on my end. Feel free to make any changes without me if you need it published sooner.

Fix formatting errors in Splunk < 6.3 tutorial

---

_integrations/agent-common/configure-agent/permissions.md

fixed tutorial bug with usermod

---

_integrations/solarwinds.md

Update SolarWinds integration to use utility

---

_integrations/datadog.md

added datadog's alert_query to the tutorial's payload

---

_integrations/jira.md
_integrations/solarwinds.md

@shaharke @dshush please review (see email)

EnableComp feedback from Brad, Joshua

---

_integrations/datadog.md

@m3nadav @dshush please review & merge or let me know if changes are required. Thanks!

Minor clean up to Datadog tutorial

---

_integrations/ansible.md

I added a note there and I'm not sure about its phrasing. Thoughts?
@shush @rasienko

Stop the use of deployment object in ansible module

---

_integrations/pingdom.md

@erikzaadi quick review /cc @michallevin

Change link to pingdom migration doc

---

_integrations/scom.md

add scom steps

---

_integrations/scom.md

Add proxy details to SCOM tutorial

---

_integrations/api-bash.md

Used monospace font for the status examples. @erikzaadi, it's a minor change, but it's ready for your review! Thanks!

Format Changes

---

_integrations/deploymentsapi.md

@rasienko this is what I've changed so far. Thoughts?

Aymohammed deployments 1

---

_integrations/api.md

Changed the language of the listed items to match the docs [page](https://www.bigpanda.io/docs/display/BD/POST+alerts). Also, added a few contextual links to that page for customer reference. Please review @erikzaadi.
Thanks!

Changes for Product&Documentation Consistency

---

_integrations/api-bash.md
_integrations/api-python.md
_integrations/api.md
_integrations/bash.md
_integrations/deploymentsapi.md
_integrations/python.md
_integrations/ruby.md

@erikzaadi last set of changes to close out this story. Pls review and merge..thx!

Edits to in-product API tutorials

---

_integrations/scom.md

@erikzaadi @cadurik please review & merge if ok. Thanks!

SCOM tutorial edits

---

_integrations/webhook.md

@geymed some text updates to the tutorial to support the new design with optional custom headers. please review and let me know what you think. FYI...Benjamin approved my mockup, but I can't seem to mention him here, so maybe he doesn't have access to this repo yet

Update webhook tutorial for new design

---

_integrations/scom.md

@erikzaadi please review & merge...thanks!

Minor edit

---

_integrations/appdynamicsapi.md

* Display Name
* bp_event_type
@dshush @shaharke

New template for appdynamics

---

_integrations/splunk-6-3-and-up.md

@erikzaadi Please review and merge. Let me know if changes are required. Thanks!

Rasienko splunk edits

---

_integrations/newrelic-new.md
_integrations/newrelic.md

New integration instructions to New Relic Legacy Alerting
Jira issue key BUG-229

Update instructions to New Relic Alerting

---

.gitignore
_integrations/agent-common/configure-agent-actions/generic.md
_integrations/agent-common/configure-agent-actions/start-centos.md
_integrations/agent-common/configure-agent-actions/start-debian.md
_integrations/agent-common/configure-agent-actions/start-redhat.md
_integrations/agent-common/configure-agent-actions/start-ubuntu.md
_integrations/agent-common/configure-agent/nagios_notifications.md
_integrations/agent-common/start-and-summary/test-and-success.md
_integrations/nagios-centos.md
_integrations/nagios-debian.md
_integrations/nagios-ubuntu.md
_integrations/nagios.md

Update from log integration to notification integration
Resolve INT-101

update nagios to notification integration

---

_integrations/solarwinds.md

@erikzaadi please review and merge. Let me know if you need any additional info. Thanks!

SolarWinds tutorial updates BUG-374

---

_integrations/agent-common/configure-agent-actions/generic.md

Update Nagios Integration Instructions

---

_integrations/api.md

Fix broken alerts api link

---

_integrations/webhook.md

Fix webhook docs link

---

_integrations/snmp-centos.md
_integrations/snmp-debian.md
_integrations/snmp-ubuntu.md
_integrations/snmp.md

Small fix to snmp integration docs

---

_integrations/snmp-centos.md
_integrations/snmp-debian.md
_integrations/snmp-ubuntu.md
_integrations/snmp.md

Corrections and additions to SNMP integration docs

---

_integrations/snmp.md

Add sudo to commands in the docs

---

_integrations/solarwinds.md

Updated solarwinds doc link

---

_integrations/solarwinds.md

Changed link to the correct url
